# -*- coding: utf-8 -*-
"""
/***************************************************************************
 bielefeldGeosuche
                                 A QGIS plugin
 This Plugin brings the great and industry-changing search functionality from the well known bielefeldGEOCLIENT to QGIS ;-)This Plugin brings the great and industry-changing search functionality from the well known bielefeldGEOCLIENT to QGIS ;-)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-24
        copyright            : (C) 2026 by Marcel Tesch (620.12)
        email                : marcel.tesch@bielefeld.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface: 'QgsInterface') -> 'bielefeldGeosuche':  # pylint: disable=invalid-name
    """Lädt die Plugin-Klasse bielefeldGeosuche und gibt eine Instanz zurück.

    Args:
        iface (QgsInterface): Eine QGIS-Interface-Instanz.

    Returns:
        bielefeldGeosuche: Eine neue Instanz des Plugins.
    """
    #
    from .bielefeld_geosuche import bielefeldGeosuche
    return bielefeldGeosuche(iface)
