# -*- coding: utf-8 -*-
"""
/***************************************************************************
 bielefeldGeosuche
                                 A QGIS plugin
 This Plugin brings the great and industry-changing search functionality from the well known bielefeldGEOCLIENT to QGIS ;-)This Plugin brings the great and industry-changing search functionality from the well known bielefeldGEOCLIENT to QGIS ;-)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-24
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Marcel Tesch (620.12)
        email                : marcel.tesch@bielefeld.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from __future__ import annotations

import os
import platform
import json
from typing import Optional

from qgis.PyQt.QtWidgets import QLineEdit, QToolBar, QMessageBox, QCompleter, QMenu, QAction
from qgis.PyQt.QtCore import Qt, QStringListModel, QUrl, QTimer, QPoint
from qgis.PyQt.QtNetwork import QNetworkAccessManager, QNetworkRequest, QNetworkReply
from qgis.gui import QgsRubberBand
from qgis.PyQt.QtGui import QColor, QFont, QIcon, QPixmap, QPainter, QFontMetrics
from configparser import ConfigParser
from .canvas_click_filter import CanvasClickFilter
from .highlight_delegate import HighlightDelegate
from .search_line_edit import SearchLineEdit

from qgis.core import (
    QgsGeometry,
    QgsInterface,
    QgsMessageLog,
    Qgis,
    QgsWkbTypes
)

from qgis.utils import iface

class bielefeldGeosuche:
    """QGIS-Plugin zur Geosuche in Bielefeld.

    Stellt eine Symbolleiste mit einem Sucheingabefeld bereit, das über die
    bielefeldGEOSUCHE-API nach Adressen, Flurstücken, Koordinaten und
    weiteren Themen sucht. Suchergebnisse werden als Autovervollständigung
    angezeigt und auf der Karte als RubberBand-Markierung hervorgehoben.
    """

    def __init__(self, iface: QgsInterface) -> None:
        """Konstruktor.

        Args:
            iface (QgsInterface): Eine QGIS-Interface-Instanz, die den Zugriff
                auf die QGIS-Anwendung zur Laufzeit ermöglicht.
        """
        # Save reference to the QGIS interface
        self.iface = iface
        self.toolbar = None
        self.line_edit = None

        # Variablen für Request-Tracking, damit alte langsame Antworten nicht neuere überschreiben
        self.current_reply = None
        self.current_request_id = 0

        # zur temporären Anzeige eines Suchergebnisses
        self.rubber_band = None

        # zum temporären Speichern des Suchbegriffes
        self.current_search_term = ""

        self.last_result_count = 0

        self.search_modes = {
            "bielefeldGEOSUCHE": "search",
            "Katalog-Suche Flurstück": "parcel",
            "Katalog-Suche Adresse": "address"
        }

        self.current_search_mode = "search"
        self.current_catalog_step = ""

        self.gemarkung = ""
        self.anfangsbuchstabe = ""

        menu = QMenu()

        for label, value in self.search_modes.items():
            action = QAction(label, self.iface.mainWindow())
            action.setCheckable(True)
            if value == "search":
                action.setChecked(True)
            action.triggered.connect(
                lambda checked, v=value: self.set_search_mode(v)
            )
            menu.addAction(action)

        self.search_mode_menu = menu
        self.search_mode_menu.aboutToShow.connect(self.on_menu_open)
        self.search_mode_menu.aboutToHide.connect(self.on_menu_close)

        self.plugin_dir = os.path.dirname(__file__)

        self.network_manager = QNetworkAccessManager()
        self.network_manager.finished.connect(self.handle_response)

        self.completer = None
        self.model = QStringListModel()

        self.search_results = {}  # label → wkt mapping
        self.typing_timer = QTimer()
        self.typing_timer.setInterval(300)  # 300ms debounce
        self.typing_timer.setSingleShot(True)
        self.typing_timer.timeout.connect(self.perform_search)

    # -------------------------
    # GUI
    # -------------------------
    def initGui(self) -> None:
        """Erstellt und registriert die grafischen Bedienelemente des Plugins.

        Fügt eine Symbolleiste mit einem Sucheingabefeld, einem Dropdown-Menü
        zur Auswahl des Suchmodus sowie einem Autovervollständiger hinzu.
        Installiert außerdem den Ereignisfilter auf dem Kartenausschnitt.
        """
        self.toolbar = QToolBar("bielefeldGEOSUCHE")
        self.iface.addToolBar(self.toolbar)

        self.line_edit = SearchLineEdit(self)
        self.line_edit.setPlaceholderText("bielefeldGEOSUCHE...")
        self.line_edit.setMaximumWidth(250)
        self.line_edit.setClearButtonEnabled(True)

        font = self.line_edit.font()
        font.setPointSize(font.pointSize() + 10)

        palette = self.line_edit.palette()
        normal_color = palette.color(palette.Text)
        hover_color = palette.color(palette.Highlight)

        self.icon_normal = self.create_text_icon("▾", font, normal_color)
        self.icon_active = self.create_text_icon("▾", font, hover_color)

        self.dropdown_action = self.line_edit.addAction(
            self.icon_normal,
            QLineEdit.TrailingPosition
        )

        self.dropdown_action.triggered.connect(self.show_search_menu)

        # während des Tippens reagieren
        self.line_edit.textEdited.connect(self.on_text_edited)

        self.toolbar.addWidget(self.line_edit)

        # Completer
        self.completer = QCompleter()
        self.completer.setModel(self.model)
        #self.completer.setFilterMode(Qt.MatchWildcard)
        self.completer.setCaseSensitivity(Qt.CaseInsensitive)
        self.completer.activated.connect(self.result_selected)
        self.completer.setCompletionMode(QCompleter.UnfilteredPopupCompletion)
        self.completer.setWrapAround(True)
        
        self.delegate = HighlightDelegate(self)
        self.completer.popup().setItemDelegate(self.delegate)
        self.completer.popup().setWordWrap(False)
        self.completer.popup().setMinimumWidth(300)

        self.line_edit.setCompleter(self.completer)

        self.click_filter = CanvasClickFilter(self)
        self.iface.mapCanvas().viewport().installEventFilter(self.click_filter)

    # -----------------------------
    # Plugin entfernen
    # -----------------------------
    def unload(self) -> None:
        """Entfernt das Plugin und bereinigt alle registrierten Ressourcen.

        Deinstalliert den Ereignisfilter vom Kartenausschnitt und
        entfernt die Symbolleiste aus der QGIS-Oberfläche.
        """
        if hasattr(self, "click_filter"):
            self.iface.mapCanvas().viewport().removeEventFilter(self.click_filter)
        
        if self.toolbar:
            self.toolbar.hide()
            self.toolbar.setParent(None)

    # -------------------------
    # Tipp-Event (Debounce)
    # -------------------------
    def on_text_edited(self, text: str) -> None:
        """Reagiert auf Benutzereingaben im Suchfeld mit Entprellungs-Logik.

        Löscht eine vorhandene RubberBand-Markierung, speichert den aktuellen
        Suchbegriff und startet den Debounce-Timer, sofern der Text mindestens
        3 Zeichen lang ist.

        Args:
            text (str): Der aktuell eingegebene Suchtext.
        """
        # Alte Markierung entfernen
        self.clear_rubber_band()

        # Suchbegriff merken
        self.current_search_term = text

        if len(text) == 0:
            self.reset_completer()

        if len(text) < 3:
            return
        self.typing_timer.start()

    # -------------------------
    # Webrequest
    # -------------------------
    def perform_search(self) -> None:
        """Sendet eine asynchrone Suchanfrage an die bielefeldGEOSUCHE-API.

        Baut die Anfrage-URL abhängig vom aktiven Suchmodus (Freitext,
        Flurstück oder Adresse) zusammen, setzt einen angepassten
        User-Agent-Header und weist der Anfrage eine eindeutige ID zu,
        um Race Conditions bei mehreren gleichzeitigen Anfragen zu vermeiden.
        """
        search_text = self.current_search_term
        if self.current_search_mode == "search" and not search_text:
            return

        # Alte Anfrage abbrechen
        #if self.current_reply is not None:
        #    self.current_reply.abort()
        #    self.current_reply.deleteLater()
        #    self.current_reply = None

        # Neue Request-ID erzeugen
        self.current_request_id += 1
        request_id = self.current_request_id

        # Infos für einen angepassten User-Agent sammeln
        qgis_version = Qgis.QGIS_VERSION
        os_info = platform.system() + " " + platform.release()
        python_version = platform.python_version()
        plugin_name = self.get_plugin_name()
        plugin_version = self.get_plugin_version()

        user_agent = (
            f"{plugin_name}/{plugin_version} "
            f"(QGIS {qgis_version}; "
            f"{os_info}; "
            f"Python {python_version})"
        )

        if self.current_search_mode == "search":
            self.current_catalog_step = ""
            url = QUrl(f"https://stadtplan.bielefeld.de/search/?maxresults=20&term={search_text}")
        elif self.current_search_mode == "parcel":
            key = ""
            if search_text in self.search_results:
                key = self.search_results[search_text]
            url = QUrl(f"https://stadtplan.bielefeld.de/search/?catalog={self.current_catalog_step}&term={key}")
        elif self.current_search_mode == "address":
            key = ""
            if search_text in self.search_results:
                key = self.search_results[search_text]
            url = QUrl(f"https://stadtplan.bielefeld.de/search/?catalog={self.current_catalog_step}&term={key}")

        
        request = QNetworkRequest(url)
        request.setRawHeader(
            b"User-Agent",
            user_agent.encode("utf-8")
        )

        reply = self.network_manager.get(request)

        # Reply + ID speichern
        reply.request_id = request_id
        self.current_reply = reply

    # -------------------------
    # Antwort verarbeiten
    # -------------------------
    def handle_response(self, reply: QNetworkReply) -> None:
        """Verarbeitet die Antwort einer abgeschlossenen Netzwerkanfrage.

        Ignoriert veraltete Antworten anhand der Request-ID, prüft auf
        Netzwerkfehler und befüllt das Autovervollständigungs-Modell mit
        den zurückgelieferten Suchergebnissen.

        Args:
            reply (QNetworkReply): Das abgeschlossene Netzwerkantwort-Objekt.
        """
        # Wenn es nicht die aktuellste Anfrage ist → ignorieren
        if not hasattr(reply, "request_id"):
            return

        if reply.request_id != self.current_request_id:
            reply.deleteLater()
            return

        # Netzwerkfehler prüfen
        if reply.error():
            QMessageBox.warning(None, "Netzwerkfehler", reply.errorString())
            reply.deleteLater()
            return

        try:
            data = json.loads(bytes(reply.readAll()).decode("utf-8"))
        except Exception:
            reply.deleteLater()
            return

        reply.success = True
        if len(data) == 0:
            reply.success = False
            reply.deleteLater()
            return

        labels = []
        self.search_results.clear()

        if self.current_search_mode == "search" or (self.current_search_mode == "parcel" and self.current_catalog_step == "getflurstuecke") or (self.current_search_mode == "address" and self.current_catalog_step == "gethausnummern"):
            for item in data:
                label = item["label"]# + " - " + str(item["sml"])
                wkt = item["geom"]

                labels.append(label)
                self.search_results[label] = wkt
        elif self.current_search_mode == "parcel":
            for item in data:
                label = item["label"]# + " - " + str(item["sml"])
                key = item["key"]

                labels.append(label)
                self.search_results[label] = key
        elif self.current_search_mode == "address":
            for item in data:
                label = item["label"]# + " - " + str(item["sml"])
                key = item["key"]

                labels.append(label)
                self.search_results[label] = key

        self.model.setStringList(labels)
        self.last_result_count = len(labels)

        # Dropdown automatisch öffnen
        self.completer.complete()

        reply.deleteLater()

    # -------------------------
    # Auswahl eines Ergebnisses
    # -------------------------
    def result_selected(self, text: str) -> None:
        """Verarbeitet die Auswahl eines Suchergebnisses aus dem Autovervollständiger.

        Zoomt bei einem Freitext-Ergebnis oder einem abschließenden
        Katalog-Schritt direkt auf die WKT-Geometrie. Bei der Katalog-Suche
        (Flurstück/Adresse) wird der nächste Katalog-Schritt ausgelöst und
        eine neue Suchanfrage gesendet.

        Args:
            text (str): Der ausgewählte Anzeigetext des Suchergebnisses.
        """
        self.current_search_term = text

        if text not in self.search_results:
            return
        
        if self.current_search_mode == "search" or (self.current_search_mode == "parcel" and self.current_catalog_step == "getflurstuecke") or (self.current_search_mode == "address" and self.current_catalog_step == "gethausnummern"):
            wkt_string = self.search_results[text]
            self.zoom_to_wkt(wkt_string)
        elif self.current_search_mode == "parcel":
            if self.current_catalog_step == "getgemarkungen":
                self.current_catalog_step = "getflure"
                self.gemarkung = text
                QTimer.singleShot(0, lambda: self.line_edit.setText(self.gemarkung))
            elif self.current_catalog_step == "getflure":
                self.current_catalog_step = "getflurstuecke"
                QTimer.singleShot(0, lambda: self.line_edit.setText(self.gemarkung + " - " + text))
            self.perform_search()
        elif self.current_search_mode == "address":
            if self.current_catalog_step == "getbuchstaben":
                self.current_catalog_step = "getstrassen"
                self.anfangsbuchstabe = text
                QTimer.singleShot(0, lambda: self.line_edit.setText(self.anfangsbuchstabe))
            elif self.current_catalog_step == "getstrassen":
                if self.current_reply.success:
                    self.current_catalog_step = "gethausnummern"
                    QTimer.singleShot(0, lambda: self.line_edit.setText(self.anfangsbuchstabe + " - " + text))
            self.perform_search()

        

    # -----------------------------
    # Auf WKT zoomen
    # -----------------------------
    def zoom_to_wkt(self, wkt_string: str) -> None:
        """Zoomt auf eine WKT-Geometrie und stellt sie als RubberBand dar.

        Entfernt zunächst eine vorhandene Markierung, erzeugt dann eine neue
        RubberBand abhängig vom Geometrietyp (Punkt: SVG-Symbol, sonst:
        Fläche/Linie) und setzt den Kartenausschnitt auf die Bounding Box
        der Geometrie.

        Args:
            wkt_string (str): WKT-Geometrie-String im Koordinatensystem der Karte.
        """
        # Fokus vom LineEdit entfernen
        self.line_edit.clearFocus()

        # Optional: Fokus explizit zurück zur Karte
        self.iface.mapCanvas().setFocus()

        geom = QgsGeometry.fromWkt(wkt_string)

        if geom.isEmpty():
            QMessageBox.warning(None, "Fehler", "Ungültige WKT-Geometrie.")
            return

        # Falls WKT in WGS84 vorliegt:
        #ource_crs = QgsCoordinateReferenceSystem("EPSG:4326")
        #dest_crs = self.iface.mapCanvas().mapSettings().destinationCrs()

        #if source_crs != dest_crs:
        #    transform = QgsCoordinateTransform(
        #        source_crs,
        #        dest_crs,
        #        QgsProject.instance()
        #    )
        #    geom.transform(transform)

        extent = geom.boundingBox()

        # Alte Markierung entfernen
        self.clear_rubber_band()

        # Neue RubberBand erzeugen
        geometry_type = QgsWkbTypes.geometryType(geom.wkbType())

        self.rubber_band = QgsRubberBand(
            self.iface.mapCanvas(),
            geometry_type
        )

        self.rubber_band.setToGeometry(geom, None)

        # Styling abhängig vom Geometrietyp
        if geometry_type == QgsWkbTypes.PointGeometry:
            svg_path = os.path.join(self.plugin_dir, "geocoder-marker.svg")

            self.rubber_band.setSvgIcon(svg_path, QPoint(-16, -50))

            self.rubber_band.show()

        else:
            self.rubber_band.setFillColor(QColor(255, 255, 255, 100))
            self.rubber_band.setStrokeColor(QColor(255, 0, 0, 100))
            self.rubber_band.setWidth(10)


        # Maßstab setzen (z.B. 1:500)
        self.iface.mapCanvas().zoomScale(1000)

        # auf Extent zoomen, durch den Zoom ist er zunächst auf 1000, so dass Punktgeometrien im Maßstab 1000 angezeigt werden
        # Bei Linien und Polygone wird auf den Extent gezoomt
        self.iface.mapCanvas().setExtent(extent)
        self.iface.mapCanvas().refresh()

    # -----------------------------
    # RubberBand sauber zurücksetzen
    # -----------------------------
    def clear_rubber_band(self) -> None:
        """Entfernt die aktuelle RubberBand-Markierung und aktualisiert die Karte."""
        if self.rubber_band:
            self.rubber_band.reset()
            self.rubber_band = None
            self.iface.mapCanvas().refresh()

    # -----------------------------
    # Lese die aktuelle Version dieses QGIS Plugins aus
    # -----------------------------
    def get_plugin_version(self) -> str:
        """Liest die Versionsnummer des Plugins aus der metadata.txt aus.

        Returns:
            str: Die Versionsnummer des Plugins, oder 'unknown' bei Fehler.
        """
        config = ConfigParser()
        metadata_path = os.path.join(
            os.path.dirname(__file__),
            "metadata.txt"
        )
        config.read(metadata_path)
        return config.get("general", "version", fallback="unknown")
    

    # -----------------------------
    # Lese den Namen dieses QGIS Plugins aus
    # -----------------------------
    def get_plugin_name(self) -> str:
        """Liest den Namen des Plugins aus der metadata.txt aus.

        Returns:
            str: Der Name des Plugins, oder 'unknown' bei Fehler.
        """
        config = ConfigParser()
        metadata_path = os.path.join(
            os.path.dirname(__file__),
            "metadata.txt"
        )
        config.read(metadata_path)
        return config.get("general", "name", fallback="unknown")


    def show_search_menu(self) -> None:
        """Zeigt das Dropdown-Menü zur Auswahl des Suchmodus an.

        Das Menü wird unterhalb der rechten Seite des Sucheingabefeldes
        positioniert.
        """
        global_pos = self.line_edit.mapToGlobal(
            self.line_edit.rect().bottomRight()
        )
        self.search_mode_menu.exec_(global_pos)


    def set_search_mode(self, mode: str) -> None:
        """Wechselt den aktiven Suchmodus und passt die Oberfläche an.

        Setzt den Completer zurück, aktualisiert den Haken im Menü und
        stellt Platzhaltertext sowie Eingabe-Modus passend zum gewählten
        Modus ein. Bei Katalog-Suchen (Flurstück/Adresse) wird sofort
        eine erste Anfrage ohne Suchtext gesendet.

        Args:
            mode (str): Der neue Suchmodus ('search', 'parcel' oder 'address').
        """
        self.current_search_mode = mode

        # Wenn der Suchmodus gewechselt wird, nmüssen die alte Suche und die alten Ergebnisse zurückgesetzt werden
        self.reset_completer()

        # Menü-Haken aktualisieren
        for action in self.search_mode_menu.actions():
            action.setChecked(
                self.search_modes[action.text()] == mode
            )

        # Placeholder und catalog_step ändern
        if mode == "search":
            self.line_edit.setReadOnly(False)
            self.line_edit.setClearButtonEnabled(True)
            self.line_edit.setPlaceholderText("bielefeldGEOSUCHE")
        elif mode == "parcel":
            self.line_edit.setReadOnly(True)
            self.line_edit.setClearButtonEnabled(False)
            self.line_edit.setPlaceholderText("Katalog-Suche Flurstück")
            self.current_catalog_step = "getgemarkungen"
        elif mode == "address":
            self.line_edit.setReadOnly(True)
            self.line_edit.setClearButtonEnabled(False)
            self.line_edit.setPlaceholderText("Katalog-Suche Adresse")
            self.current_catalog_step = "getbuchstaben"

        # für die Katalog-Suche direkt eine neue Suche starten, da hier schon Ergebnisse ohne Suchtext ausgegeben werden müssen
        if mode == "parcel" or mode == "address":
            self.perform_search()


    def create_text_icon(self, text: str, font: QFont, color: QColor) -> QIcon:
        """Erzeugt ein QIcon aus einem Text-Zeichen mit gegebener Schrift und Farbe.

        Zeichnet das Zeichen zentriert auf ein transparentes 16x16-Pixel-Pixmap.

        Args:
            text (str): Das darzustellende Zeichen (z. B. ein Unicode-Symbol).
            font (QFont): Die zu verwendende Schriftart.
            color (QColor): Die Farbe des Zeichens.

        Returns:
            QIcon: Das erzeugte Icon.
        """
        size = 16
        pixmap = QPixmap(size, size)
        pixmap.fill(Qt.transparent)

        painter = QPainter(pixmap)
        painter.setRenderHint(QPainter.Antialiasing)
        painter.setPen(color)
        painter.setFont(font)

        fm = QFontMetrics(font)

        text_width = fm.horizontalAdvance(text)
        #text_height = fm.height()

        x = (size - text_width) / 2

        # Optische Vertikal-Zentrierung über Baseline
        y = (size + fm.ascent() - fm.descent()) / 2

        painter.drawText(int(x), int(y), text)
        painter.end()

        return QIcon(pixmap)

    def on_menu_open(self) -> None:
        """Wechselt das Dropdown-Symbol zur aktiven Darstellung beim Öffnen des Menüs."""
        self.dropdown_action.setIcon(self.icon_active)

    def on_menu_close(self) -> None:
        """Stellt das Dropdown-Symbol auf die normale Darstellung zurück."""
        self.dropdown_action.setIcon(self.icon_normal)

    def on_popup_closed(self) -> None:
        """Gibt den Fokus vom Sucheingabefeld zurück an den Kartenausschnitt."""
        # Fokus vom LineEdit entfernen
        self.line_edit.clearFocus()

        # Optional: Fokus explizit zurück zur Karte
        self.iface.mapCanvas().setFocus()

    def reset_completer(self) -> None:
        """Setzt den Autovervollständiger und alle Suchzustände vollständig zurück.

        Löscht den Suchbegriff, die Gemarkung, den Anfangsbuchstaben und die
        Ergebnisanzahl. Schließt das Popup, leert das Eingabefeld, entfernt
        eine vorhandene RubberBand-Markierung und leert das Datenmodell.
        """
        self.current_search_term = ""
        self.gemarkung = ""
        self.anfangsbuchstabe = ""
        self.last_result_count = 0
        
        # Alte Markierung entfernen
        self.clear_rubber_band()  

        popup = self.completer.popup()

        # Popup schließen
        popup.hide()

        # Selektion entfernen
        popup.setCurrentIndex(popup.model().index(-1, -1))
        self.line_edit.clear()

        # Completion Prefix leeren
        self.completer.setCompletionPrefix("")

        # Modell leeren (optional)
        self.model.setStringList([])