# -*- coding: utf-8 -*-
"""
/***************************************************************************
 bielefeldGeosuche
                                 A QGIS plugin
 This Plugin brings the great and industry-changing search functionality from the well known bielefeldGEOCLIENT to QGIS ;-)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-24
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Amt für Geoinformation und Kataster - Stadt Bielefeld
        email                : olkd@bielefeld.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
import platform
import json
import configparser

from qgis.PyQt.QtWidgets import QLineEdit, QToolBar, QMessageBox, QCompleter, QMenu, QAction
from qgis.PyQt.QtCore import Qt, QStringListModel, QUrl, QTimer, QPoint, QEventLoop, QEvent
from qgis.PyQt.QtNetwork import QNetworkAccessManager, QNetworkRequest
from qgis.gui import QgsRubberBand
from qgis.PyQt.QtGui import QColor, QIcon, QPixmap, QPainter, QFontMetrics
from qgis.PyQt.QtXml import QDomDocument
from configparser import ConfigParser
from .canvas_click_filter import CanvasClickFilter
from .popup_event_filter import PopupEventFilter
from .highlight_delegate import HighlightDelegate
from .search_line_edit import SearchLineEdit

from qgis.core import (
    QgsGeometry,
    QgsMessageLog,
    Qgis,
    QgsWkbTypes,
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
    QgsProject,
    QgsRasterLayer,
    QgsVectorLayer
)

from qgis.utils import iface

class bielefeldGeosuche:
    """QGIS-Plugin zur Geosuche in Bielefeld.

    Stellt eine Symbolleiste mit einem Sucheingabefeld, zum Hinzufügen 
    direkt in die Werkzeugleiste bereit, das über die
    bielefeldGEOSUCHE-API nach Adressen, Flurstücken, Koordinaten und
    weiteren Themen sucht. Suchergebnisse werden als Autovervollständigung
    angezeigt und auf der Karte als RubberBand-Markierung hervorgehoben.
    """

    def __init__(self, iface):
        """Konstruktor.

        Args:
            iface (QgsInterface): Eine QGIS-Interface-Instanz, die den Zugriff
                auf die QGIS-Anwendung zur Laufzeit ermöglicht.
        """
        # Flag zur Angabe, ob Debug-Meldungen geloggt werden sollen
        self.debug_log = False

        # Save reference to the QGIS interface
        self.iface = iface
        self.toolbar = None
        self.line_edit = None

        # Variablen für Request-Tracking, damit alte langsame Antworten nicht neuere überschreiben
        self.current_reply = None
        self.current_request_id = 0

        # zur temporären Anzeige eines Suchergebnisses
        self.rubber_band = None

        # zum temporären Speichern des Suchbegriffes
        self.current_search_term = ""

        # Anzahl der letzten Suchergebnisse
        self.last_result_count = 0

        # Verfügbare Suchmodi
        # search ist eine ganz normale Suche per Eingabe und Autovervollständigung
        # die parcel und address Suche ist eine "Schritt für Schritt"-Suche. Hier werden nacheinander Ergebnisse aus einer vorgegebenen Liste ausgewählt.
        # die Suchmodi WMS und WFS zeigen alle Dienste aus dem Bielefelder geoKATALOG an und bieten die Möglichkeit diese simpel hinzuzuladen
        self.search_modes = {
            "bielefeldGEOSUCHE": "search",
            "Katalog-Suche Flurstück": "parcel",
            "Katalog-Suche Adresse": "address",
            "geoKATALOG WMS-Suche": "wms",
            "geoKATALOG WFS-Suche": "wfs"
        }

        # der Standard-Suchmouds ist search
        self.current_search_mode = "search"

        # zum temporären Speichern des aktuellen bzw. nächsten Suchschrittes
        self.current_catalog_step = ""

        # zur Anzeige der ersten ausgewählten Suchparameters bei der "Schritt für Schritt"-Suche
        self.gemarkung = ""
        self.anfangsbuchstabe = ""

        # Erstellen eines Menüs zum Wechseln des Suchmodus
        menu = QMenu()

        for label, value in self.search_modes.items():
            action = QAction(label, self.iface.mainWindow())
            action.setCheckable(True)
            if value == "search":
                action.setChecked(True)
            action.triggered.connect(
                lambda checked, v=value: self.set_search_mode(v)
            )
            menu.addAction(action)

        self.search_mode_menu = menu
        self.search_mode_menu.aboutToShow.connect(self.on_menu_open)
        self.search_mode_menu.aboutToHide.connect(self.on_menu_close)

        self.plugin_dir = os.path.dirname(__file__)

        # hole dir die WMS und WFS geoKATALOG URL aus der config.ini
        config = configparser.ConfigParser()
        config_path = os.path.join(self.plugin_dir, "config.ini")
        config.read(config_path, encoding="utf-8")

        self.wms_geocatalog_url = config.get("paths", "wms_geocatalog_url")
        self.wfs_geocatalog_url = config.get("paths", "wfs_geocatalog_url")

        self.network_manager = QNetworkAccessManager()
        self.network_manager.finished.connect(self.handle_response)

        # Infos für einen angepassten User-Agent sammeln
        qgis_version = Qgis.QGIS_VERSION
        os_info = platform.system() + " " + platform.release()
        python_version = platform.python_version()
        plugin_name = self.get_plugin_name()
        plugin_version = self.get_plugin_version()

        self.user_agent = (
            f"{plugin_name}/{plugin_version} "
            f"(QGIS {qgis_version}; "
            f"{os_info}; "
            f"Python {python_version})"
        )

        # Completer für die Autovervollständigung von Suchergebnissen
        self.completer = None
        self.model = QStringListModel()

        # zum temporären Speichern der aktuellen Suchergebnisse
        self.search_results = {}  # label → wkt mapping
        self.search_metadata = {}  # label → metadata_url

        # Timer, für das Absenden einer Suchanfrage an den Suchdienst, nachdem im Text-Eingabefeld getippt wurde
        # Sinnvoll zur Reduzierung von ausgehenden Such-Requests. Gibt dem Nutzer die Möglichkeit einen Suchterm
        # zu formulieren, ohne dass bereits nach jedem getippten Buchstaben Such-Requests ausgeführt werden.
        self.typing_timer = QTimer()
        self.typing_timer.setInterval(300)  # 300ms debounce
        self.typing_timer.setSingleShot(True)
        self.typing_timer.timeout.connect(self.perform_search)


    def initGui(self):
        """Erstellt und registriert die grafischen Bedienelemente des Plugins.

        Fügt eine Symbolleiste mit einem Sucheingabefeld, einem Dropdown-Menü
        zur Auswahl des Suchmodus sowie einem Autovervollständiger hinzu.
        Installiert außerdem den Ereignisfilter auf dem Kartenausschnitt.
        """
        self.toolbar = QToolBar("bielefeldGEOSUCHE")
        self.iface.addToolBar(self.toolbar)

        # das Herzstück der Suche, das Sucheingabefeld
        self.line_edit = SearchLineEdit(self)
        self.line_edit.setPlaceholderText("bielefeldGEOSUCHE...")
        self.line_edit.setMaximumWidth(250)
        self.line_edit.setClearButtonEnabled(True)

        font = self.line_edit.font()
        font.setPointSize(font.pointSize() + 10)

        palette = self.line_edit.palette()
        normal_color = palette.color(palette.Text)
        hover_color = palette.color(palette.Highlight)

        # Icon zum Aufrufen des Menüs zur Auswahl des Suchmodus
        self.icon_normal = self.create_text_icon("▾", font, normal_color)
        self.icon_active = self.create_text_icon("▾", font, hover_color)

        self.dropdown_action = self.line_edit.addAction(
            self.icon_normal,
            QLineEdit.TrailingPosition
        )

        self.dropdown_action.triggered.connect(self.show_search_menu)

        # während des Tippens reagieren
        self.line_edit.textEdited.connect(self.on_text_edited)
        self.line_edit.textChanged.connect(self.on_text_changed)

        self.toolbar.addWidget(self.line_edit)

        # Completer
        self.completer = QCompleter()
        self.completer.setModel(self.model)
        # der Completer soll keine Ergebnisse filtern, es sollen alle Ergebnisse angezeigt werden.
        #self.completer.setFilterMode(Qt.MatchWildcard)
        self.completer.setCaseSensitivity(Qt.CaseInsensitive)
        self.completer.activated.connect(self.result_selected)
        self.completer.setCompletionMode(QCompleter.UnfilteredPopupCompletion)
        # Wenn man über den letzten Eintrag in der Liste hinaus navigiert, landet man wieder beim ersten Eintrag
        self.completer.setWrapAround(True)
        
        # zur benutzerdefinierten Formatierung von Suchergebnissen
        self.delegate = HighlightDelegate(self)
        self.completer.popup().setItemDelegate(self.delegate)
        self.completer.popup().setWordWrap(True)
        self.completer.popup().setMinimumWidth(300)
        self.popup_filter = PopupEventFilter(self)
        self.completer.popup().installEventFilter(self.popup_filter)
        self.saved_scroll_pos = 0

        self.line_edit.setCompleter(self.completer)

        # Methode um Klicks in die Karte zu registrieren, um bestehende Rubberband Markierungen zu entfernen
        self.click_filter = CanvasClickFilter(self)
        self.iface.mapCanvas().viewport().installEventFilter(self.click_filter)


    def unload(self):
        """Entfernt das Plugin und bereinigt alle registrierten Ressourcen.

        Deinstalliert den Ereignisfilter vom Kartenausschnitt und
        entfernt die Symbolleiste aus der QGIS-Oberfläche.
        """
        if hasattr(self, "click_filter"):
            self.iface.mapCanvas().viewport().removeEventFilter(self.click_filter)
        
        if self.toolbar:
            self.toolbar.hide()
            self.toolbar.setParent(None)


    def on_text_edited(self, text):
        """Reagiert auf Benutzereingaben im Suchfeld mit Entprellungs-Logik.

        Löscht eine vorhandene RubberBand-Markierung, speichert den aktuellen
        Suchbegriff und startet den Debounce-Timer, sofern der Text mindestens
        3 Zeichen lang ist.

        Args:
            text (str): Der aktuell eingegebene Suchtext.
        """
        if self.debug_log:
            QgsMessageLog.logMessage(
                "on_text_edited() " + text,
                "bielefeldGeosuche",
                Qgis.Info
            )

        # Alte Markierung entfernen
        self.clear_rubber_band()

        # Suchbegriff merken
        self.current_search_term = text

        # Wenn Text leer, Completer zurücksetzen
        if len(text) == 0:
            self.reset_completer()

        # Wenn Text kürzer als 3 Zeichen, nichts tun
        if len(text) < 3:
            return
        self.typing_timer.start()


    def on_text_changed(self, text: str) -> None:
        """Wird ausgelöst, wenn sich der Inhalt des Suchfeldes ändert.

        Reserviert für zukünftige Erweiterungen. Derzeit ohne Funktion.

        Args:
            text (str): Der aktuelle Inhalt des Suchfeldes.
        """
        if self.debug_log:
            QgsMessageLog.logMessage(
                "on_text_changed() " + text,
                "bielefeldGeosuche",
                Qgis.Info
            )


    def perform_search(self):
        """Sendet eine asynchrone Suchanfrage an die bielefeldGEOSUCHE-API.

        Baut die Anfrage-URL abhängig vom aktiven Suchmodus (Freitext,
        Flurstück oder Adresse) zusammen, setzt einen angepassten
        User-Agent-Header und weist der Anfrage eine eindeutige ID zu,
        um Race Conditions bei mehreren gleichzeitigen Anfragen zu vermeiden.
        """
        search_text = self.current_search_term
        if self.debug_log:
            QgsMessageLog.logMessage(
                "perform_search() " + search_text,
                "bielefeldGeosuche",
                Qgis.Info
            )
        if self.current_search_mode == "search" and not search_text:
            return

        # Alte Anfrage abbrechen
        #if self.current_reply is not None:
        #    self.current_reply.abort()
        #    self.current_reply.deleteLater()
        #    self.current_reply = None

        # Neue Request-ID erzeugen
        self.current_request_id += 1
        request_id = self.current_request_id

        if self.debug_log:
            QgsMessageLog.logMessage(
                "perform_search() request_id " + str(request_id),
                "bielefeldGeosuche",
                Qgis.Info
            )

        if self.debug_log:
            QgsMessageLog.logMessage(
                "current_search_mode: " + self.current_search_mode + " - " + self.current_catalog_step,
                "bielefeldGeosuche",
                Qgis.Info
            )

        # Zusammensetzen der URLs je nach aktuellem Suchmodus
        if self.current_search_mode == "search":
            self.current_catalog_step = ""
            url = QUrl(f"https://stadtplan.bielefeld.de/search/?maxresults=20&term={search_text}")
        elif self.current_search_mode == "parcel":
            key = ""
            if search_text in self.search_results:
                key = self.search_results[search_text]
            url = QUrl(f"https://stadtplan.bielefeld.de/search/?catalog={self.current_catalog_step}&term={key}")
        elif self.current_search_mode == "address":
            key = ""
            if search_text in self.search_results:
                key = self.search_results[search_text]
            url = QUrl(f"https://stadtplan.bielefeld.de/search/?catalog={self.current_catalog_step}&term={key}")
        elif self.current_search_mode == "wms":
            self.current_catalog_step = ""
            url = QUrl(self.wms_geocatalog_url)
        elif self.current_search_mode == "wfs":
            self.current_catalog_step = ""
            url = QUrl(self.wfs_geocatalog_url)

        # URL absetzen
        request = QNetworkRequest(url)
        request.setRawHeader(
            b"User-Agent",
            self.user_agent.encode("utf-8")
        )

        reply = self.network_manager.get(request)

        # Reply + ID speichern
        reply.request_id = request_id
        self.current_reply = reply


    def handle_response(self, reply):
        """Verarbeitet die Antwort einer abgeschlossenen Netzwerkanfrage.

        Ignoriert veraltete Antworten anhand der Request-ID, prüft auf
        Netzwerkfehler und befüllt das Autovervollständigungs-Modell mit
        den zurückgelieferten Suchergebnissen.

        Args:
            reply (QNetworkReply): Das abgeschlossene Netzwerkantwort-Objekt.
        """
        if self.debug_log:
            QgsMessageLog.logMessage(
                "handle_response()",
                "bielefeldGeosuche",
                Qgis.Info
            )

        # Wenn es nicht die aktuellste Anfrage ist → ignorieren
        if not hasattr(reply, "request_id"):
            return

        if reply.request_id != self.current_request_id:
            reply.deleteLater()
            return

        # Netzwerkfehler prüfen
        if reply.error():
            QMessageBox.warning(None, "Netzwerkfehler", reply.errorString())
            reply.deleteLater()
            return

        try:
            data = json.loads(bytes(reply.readAll()).decode("utf-8"))
        except Exception:
            reply.deleteLater()
            return

        reply.success = True
        if len(data) == 0:
            if self.debug_log:
                QgsMessageLog.logMessage(
                    "Für den Suchbegriff \"" + self.current_search_term + "\" wurden keine Ergebnisse gefunden.",
                    "bielefeldGeosuche",
                    Qgis.Info
                )
            reply.success = False
            reply.deleteLater()
            return

        self.saved_scroll_pos = 0
        labels = []
        self.search_results.clear()
        self.search_metadata.clear()

        # Suchergebnisse auslesen und für Auswahl aufbereiten
        if self.current_search_mode == "search" or (self.current_search_mode == "parcel" and self.current_catalog_step == "getflurstuecke") or (self.current_search_mode == "address" and self.current_catalog_step == "gethausnummern"):
            for item in data:
                label = item["label"]# + " - " + str(item["sml"])
                wkt = item["geom"]

                labels.append(label)
                self.search_results[label] = wkt
        elif self.current_search_mode == "parcel":
            for item in data:
                label = item["label"]# + " - " + str(item["sml"])
                key = item["key"]

                labels.append(label)
                self.search_results[label] = key
        elif self.current_search_mode == "address":
            for item in data:
                label = item["label"]# + " - " + str(item["sml"])
                key = item["key"]

                labels.append(label)
                self.search_results[label] = key
        elif self.current_search_mode == "wms":
            for item in data:
                label = item["title"]
                key = item["url"]
                info = item["meta"]

                labels.append(label)
                self.search_results[label] = key
                self.search_metadata[label] = info
        elif self.current_search_mode == "wfs":
            for item in data:
                label = item["title"]
                key = item["url"]
                info = item["meta"]

                labels.append(label)
                self.search_results[label] = key
                self.search_metadata[label] = info

        if self.debug_log:
            QgsMessageLog.logMessage(
                "Labels: " + str(labels),
                "bielefeldGeosuche",
                Qgis.Info
            )

        self.model.setStringList(labels)
        self.last_result_count = len(labels)

        if self.debug_log:
            QgsMessageLog.logMessage(
                "self.last_result_count: " + str(self.last_result_count),
                "bielefeldGeosuche",
                Qgis.Info
            )

        # Dropdown automatisch öffnen
        self.completer.complete()

        reply.deleteLater()


    def result_selected(self, text):
        """Verarbeitet die Auswahl eines Suchergebnisses aus dem Autovervollständiger.

        Zoomt bei einem Freitext-Ergebnis oder einem abschließenden
        Katalog-Schritt direkt auf die WKT-Geometrie. Bei der Katalog-Suche
        (Flurstück/Adresse) wird der nächste Katalog-Schritt ausgelöst und
        eine neue Suchanfrage gesendet.

        Args:
            text (str): Der ausgewählte Anzeigetext des Suchergebnisses.
        """
        if self.debug_log:
            QgsMessageLog.logMessage(
                "result_selected() " + text,
                "bielefeldGeosuche",
                Qgis.Info
            )

        # Aktuell ausgewählten Suchbegriff setzen
        self.current_search_term = text

        if text not in self.search_results:
            return
        
        if self.debug_log:
            QgsMessageLog.logMessage(
                "self.current_catalog_step " + self.current_catalog_step,
                "bielefeldGeosuche",
                Qgis.Info
            )

        # entweder auf das aktuelle Suchergebnis zoomen oder den aktuellen Suchschritt ermitteln 
        # und für die Katalog-Suche den nächsten Suchschritt setzen und die Suche erneut starten
        if self.current_search_mode == "search" or (self.current_search_mode == "parcel" and self.current_catalog_step == "getflurstuecke") or (self.current_search_mode == "address" and self.current_catalog_step == "gethausnummern"):
            wkt_string = self.search_results[text]
            self.zoom_to_wkt(wkt_string)
        elif self.current_search_mode == "parcel":
            if self.current_catalog_step == "getgemarkungen":
                self.current_catalog_step = "getflure"
                self.gemarkung = text
                QTimer.singleShot(0, lambda: self.line_edit.setText(self.gemarkung))
            elif self.current_catalog_step == "getflure":
                self.current_catalog_step = "getflurstuecke"
                QTimer.singleShot(0, lambda: self.line_edit.setText(self.gemarkung + " - " + text))
            self.perform_search()
        elif self.current_search_mode == "address":
            if self.current_catalog_step == "getbuchstaben":
                self.current_catalog_step = "getstrassen"
                self.anfangsbuchstabe = text
                QTimer.singleShot(0, lambda: self.line_edit.setText(self.anfangsbuchstabe))
            elif self.current_catalog_step == "getstrassen":
                if self.current_reply.success:
                    self.current_catalog_step = "gethausnummern"
                    QTimer.singleShot(0, lambda: self.line_edit.setText(self.anfangsbuchstabe + " - " + text))
            self.perform_search()
        elif self.current_search_mode == "wms":
            wms_url = self.search_results[text]
            self.add_ows_as_group(wms_url, text)
        elif self.current_search_mode == "wfs":
            wfs_url = self.search_results[text]
            self.add_ows_as_group(wfs_url, text)

        
    def zoom_to_wkt(self, wkt_string):
        """Zoomt auf eine WKT-Geometrie und stellt sie als RubberBand dar.

        Entfernt zunächst eine vorhandene Markierung, erzeugt dann eine neue
        RubberBand abhängig vom Geometrietyp (Punkt: SVG-Symbol, sonst:
        Fläche/Linie) und setzt den Kartenausschnitt auf die Bounding Box
        der Geometrie.

        Args:
            wkt_string (str): WKT-Geometrie-String im Koordinatensystem der Karte.
        """
        if self.debug_log:
            QgsMessageLog.logMessage(
                "zoom_to_wkt()",
                "bielefeldGeosuche",
                Qgis.Info
            )

        # Fokus vom LineEdit entfernen
        self.line_edit.clearFocus()

        # Fokus explizit zurück zur Karte
        self.iface.mapCanvas().setFocus()

        # Geometrie aus WKT erstellen
        geom = QgsGeometry.fromWkt(wkt_string)

        if geom.isEmpty():
            QMessageBox.warning(None, "Fehler", "Ungültige WKT-Geometrie.")
            return

        if self.debug_log:
            QgsMessageLog.logMessage(
                "Geometrie: " + str(geom),
                "bielefeldGeosuche",
                Qgis.Info
            )

        # WKT liegt immer in UTM32 vor
        source_crs = QgsCoordinateReferenceSystem("EPSG:25832")
        dest_crs = self.iface.mapCanvas().mapSettings().destinationCrs()

        # Wenn das vom Benutzer verwendete KBS nicht UTM32 ist, transformiere die Geometrie in das
        # vom Benutzer verwendete KBS
        if source_crs != dest_crs:
            if self.debug_log:
                QgsMessageLog.logMessage(
                    "Transformiere Geometrie von: " + str(source_crs.description()) + " nach " + str(dest_crs.description()),
                    "bielefeldGeosuche",
                    Qgis.Info
                )
            transform = QgsCoordinateTransform(
                source_crs,
                dest_crs,
                QgsProject.instance()
            )
            geom.transform(transform)

        # Extent ermitteln
        extent = geom.boundingBox()

        # Alte Markierung entfernen
        self.clear_rubber_band()

        # Neues RubberBand erzeugen
        geometry_type = QgsWkbTypes.geometryType(geom.wkbType())

        self.rubber_band = QgsRubberBand(
            self.iface.mapCanvas(),
            geometry_type
        )

        self.rubber_band.setToGeometry(geom, None)

        # Styling abhängig vom Geometrietyp
        if geometry_type == QgsWkbTypes.PointGeometry:
            svg_path = os.path.join(self.plugin_dir, "geocoder-marker.svg")

            self.rubber_band.setSvgIcon(svg_path, QPoint(-16, -50))

            self.rubber_band.show()

        else:
            self.rubber_band.setFillColor(QColor(255, 255, 255, 100))
            self.rubber_band.setStrokeColor(QColor(255, 0, 0, 100))
            self.rubber_band.setWidth(10)


        # Maßstab setzen (z.B. 1:500)
        self.iface.mapCanvas().zoomScale(1000)

        # auf Extent zoomen, durch den Zoom ist er zunächst auf 1000, so dass Punktgeometrien im Maßstab 1000 angezeigt werden
        # Bei Linien und Polygone wird auf den Extent gezoomt
        self.iface.mapCanvas().setExtent(extent)
        self.iface.mapCanvas().refresh()


    def clear_rubber_band(self):
        """Entfernt die aktuelle RubberBand-Markierung und aktualisiert die Karte."""
        if self.rubber_band:
            self.rubber_band.reset()
            self.rubber_band = None
            self.iface.mapCanvas().refresh()


    def get_plugin_version(self):
        """Liest die Versionsnummer des Plugins aus der metadata.txt aus.

        Returns:
            str: Die Versionsnummer des Plugins, oder 'unknown' bei Fehler.
        """
        config = ConfigParser()
        metadata_path = os.path.join(
            os.path.dirname(__file__),
            "metadata.txt"
        )
        config.read(metadata_path)
        return config.get("general", "version", fallback="unknown")
    

    def get_plugin_name(self):
        """Liest den Namen des Plugins aus der metadata.txt aus.

        Returns:
            str: Der Name des Plugins, oder 'unknown' bei Fehler.
        """
        config = ConfigParser()
        metadata_path = os.path.join(
            os.path.dirname(__file__),
            "metadata.txt"
        )
        config.read(metadata_path)
        return config.get("general", "name", fallback="unknown")


    def show_search_menu(self):
        """Zeigt das Dropdown-Menü zur Auswahl des Suchmodus an.

        Das Menü wird unterhalb der rechten Seite des Sucheingabefeldes
        positioniert.
        """
        if self.debug_log:
            QgsMessageLog.logMessage(
                "show_search_menu()",
                "bielefeldGeosuche",
                Qgis.Info
            )

        global_pos = self.line_edit.mapToGlobal(
            self.line_edit.rect().bottomRight()
        )
        self.search_mode_menu.exec_(global_pos)


    def set_search_mode(self, mode):
        """Wechselt den aktiven Suchmodus und passt die Oberfläche an.

        Setzt den Completer zurück, aktualisiert den Haken im Menü und
        stellt Platzhaltertext sowie Eingabe-Modus passend zum gewählten
        Modus ein. Bei Katalog-Suchen (Flurstück/Adresse) wird sofort
        eine erste Anfrage ohne Suchtext gesendet.

        Args:
            mode (str): Der neue Suchmodus ('search', 'parcel' oder 'address').
        """
        if self.debug_log:
            QgsMessageLog.logMessage(
                "set_search_mode: " + mode,
                "bielefeldGeosuche",
                Qgis.Info
            )
        self.current_search_mode = mode

        if self.debug_log:
            QgsMessageLog.logMessage(
                "self.line_edit.text() " + self.line_edit.text(),
                "bielefeldGeosuche",
                Qgis.Info
            )

        # Wenn der Suchmodus gewechselt wird, nmüssen die alte Suche und die alten Ergebnisse zurückgesetzt werden
        self.reset_completer()

        if self.debug_log:
            QgsMessageLog.logMessage(
                "self.line_edit.text() " + self.line_edit.text(),
                "bielefeldGeosuche",
                Qgis.Info
            )

        # Menü-Haken aktualisieren
        for action in self.search_mode_menu.actions():
            action.setChecked(
                self.search_modes[action.text()] == mode
            )

        # Placeholder und catalog_step ändern
        if mode == "search":
            self.line_edit.setReadOnly(False)
            self.line_edit.setClearButtonEnabled(True)
            self.line_edit.setPlaceholderText("bielefeldGEOSUCHE")
        elif mode == "parcel":
            self.line_edit.setReadOnly(True)
            self.line_edit.setClearButtonEnabled(False)
            self.line_edit.setPlaceholderText("Katalog-Suche Flurstück")
            self.current_catalog_step = "getgemarkungen"
        elif mode == "address":
            self.line_edit.setReadOnly(True)
            self.line_edit.setClearButtonEnabled(False)
            self.line_edit.setPlaceholderText("Katalog-Suche Adresse")
            self.current_catalog_step = "getbuchstaben"
        elif mode == "wms":
            self.line_edit.setReadOnly(True)
            self.line_edit.setClearButtonEnabled(False)
            self.line_edit.setPlaceholderText("geoKATALOG WMS-Suche")
        elif mode == "wfs":
            self.line_edit.setReadOnly(True)
            self.line_edit.setClearButtonEnabled(False)
            self.line_edit.setPlaceholderText("geoKATALOG WFS-Suche")

        # für die Katalog-Suche und die geoKATALOG-Suche direkt eine neue Suche starten, da hier schon Ergebnisse ohne Suchtext ausgegeben werden müssen
        if mode != "search":
            self.perform_search()


    def create_text_icon(self, text, font, color):
        """Erzeugt ein QIcon aus einem Text-Zeichen mit gegebener Schrift und Farbe.

        Zeichnet das Zeichen zentriert auf ein transparentes 16x16-Pixel-Pixmap.

        Args:
            text (str): Das darzustellende Zeichen (z. B. ein Unicode-Symbol).
            font (QFont): Die zu verwendende Schriftart.
            color (QColor): Die Farbe des Zeichens.

        Returns:
            QIcon: Das erzeugte Icon.
        """
        size = 16
        pixmap = QPixmap(size, size)
        pixmap.fill(Qt.transparent)

        painter = QPainter(pixmap)
        painter.setRenderHint(QPainter.Antialiasing)
        painter.setPen(color)
        painter.setFont(font)

        fm = QFontMetrics(font)

        text_width = fm.horizontalAdvance(text)

        x = (size - text_width) / 2

        # Optische Vertikal-Zentrierung über Baseline
        y = (size + fm.ascent() - fm.descent()) / 2

        painter.drawText(int(x), int(y), text)
        painter.end()

        return QIcon(pixmap)


    def on_menu_open(self):
        """Wechselt das Dropdown-Symbol zur aktiven Darstellung beim Öffnen des Menüs."""
        self.dropdown_action.setIcon(self.icon_active)


    def on_menu_close(self):
        """Stellt das Dropdown-Symbol auf die normale Darstellung zurück."""
        self.dropdown_action.setIcon(self.icon_normal)


    def reset_completer(self):
        """Setzt den Autovervollständiger und alle Suchzustände vollständig zurück.

        Löscht den Suchbegriff, die Gemarkung, den Anfangsbuchstaben und die
        Ergebnisanzahl. Schließt das Popup, leert das Eingabefeld, entfernt
        eine vorhandene RubberBand-Markierung und leert das Datenmodell.
        """
        if self.debug_log:
            QgsMessageLog.logMessage(
                "reset_completer()",
                "bielefeldGeosuche",
                Qgis.Info
            )
        self.current_search_term = ""
        self.gemarkung = ""
        self.anfangsbuchstabe = ""
        self.last_result_count = 0
        
        # Alte Markierung entfernen
        self.clear_rubber_band()  

        popup = self.completer.popup()

        # Popup schließen
        popup.hide()

        # Selektion entfernen
        popup.setCurrentIndex(popup.model().index(-1, -1))
        self.line_edit.clear()

        # Completion Prefix leeren
        self.completer.setCompletionPrefix("")

        # Modell leeren (optional)
        self.model.setStringList([])

    
    def add_ows_as_group(self, ows_url, group_name):
        """Lädt einen WMS oder WFS in das Projekt.

        Args:
            ows_url (str): URL des hinzuzuladenden Dienstes.
            group_name (str): Gruppenname des hinzuzuladenden Dienstes.
        """
        ows_type = self.current_search_mode.upper()

        if self.debug_log:
            QgsMessageLog.logMessage(
                "add_ows_as_group() group_name=" + group_name + ", ows_url=" + ows_url + ", ows_type: " + ows_type,
                "bielefeldGeosuche",
                Qgis.Info
            )

        # 1. GetCapabilities URL zusammenbauen
        capabilities_url = ""

        pos = ows_url.find("?")

        if pos != -1:
            if pos == (len(ows_url)-1):
                capabilities_url = f"{ows_url}SERVICE={ows_type}&REQUEST=GetCapabilities"
            else:
                capabilities_url = f"{ows_url}&SERVICE={ows_type}&REQUEST=GetCapabilities"
        else:
            # Kein Fragezeichen enthalten
            capabilities_url = f"{ows_url}?SERVICE={ows_type}&REQUEST=GetCapabilities"

        if self.debug_log:
            QgsMessageLog.logMessage(
                "add_ows_as_group() capabilities_url=" + capabilities_url,
                "bielefeldGeosuche",
                Qgis.Info
            )

        # 2. Netzwerk-Request vorbereiten
        manager = QNetworkAccessManager()
        request = QNetworkRequest(QUrl(capabilities_url))
        request.setRawHeader(
            b"User-Agent",
            self.user_agent.encode("utf-8")
        )
        reply = manager.get(request)

        # 3. Synchron warten (wichtig!)
        loop = QEventLoop()
        reply.finished.connect(loop.quit)
        loop.exec_()

        # Netzwerkfehler prüfen
        if reply.error():
            QMessageBox.warning(None, "Netzwerkfehler", reply.errorString())
            reply.deleteLater()
            return

        xml_data = reply.readAll().data()

        # 4. XML parsen
        doc = QDomDocument()
        if not doc.setContent(xml_data):
            raise Exception("Capabilities XML konnte nicht geparst werden")

        # 5. Prüfen, ob das Projekt-KBS vom OWS unterstützt wird
        # Projekt-CRS
        project_crs = QgsProject.instance().crs().authid()

        firstElemName = ""
        if ows_type == "WMS":
            firstElemName = "Layer"
        elif ows_type == "WFS":
            firstElemName = "FeatureTypeList"

        root_layers = doc.elementsByTagName(firstElemName)
        
        if root_layers.count() == 0:
            raise Exception(f"Keine {firstElemName} gefunden")

        root_layer = root_layers.at(0).toElement()

        # Set umd alle CRS/SRS zu sammeln
        supported_crs = set()

        if ows_type == "WMS":
            # CRS (WMS 1.3.0)
            crs_nodes = root_layer.elementsByTagName("CRS")
            for i in range(crs_nodes.count()):
                crs_text = crs_nodes.at(i).toElement().text().strip()
                if crs_text:
                    supported_crs.add(crs_text)

            # SRS (WMS 1.1.1)
            srs_nodes = root_layer.elementsByTagName("SRS")
            for i in range(srs_nodes.count()):
                srs_text = srs_nodes.at(i).toElement().text().strip()
                if srs_text:
                    # Achtung: kann mehrere Codes enthalten (durch Leerzeichen getrennt)
                    for srs in srs_text.split():
                        supported_crs.add(srs.strip())
            
        elif ows_type == "WFS":
            for tag in ["DefaultCRS", "OtherCRS", "DefaultSRS", "OtherSRS"]:
                crs_nodes = root_layer.elementsByTagName(tag)
                for i in range(crs_nodes.count()):
                    crs_text = crs_nodes.at(i).toElement().text().strip().replace("::", ":").replace("urn:ogc:def:crs:", "").replace("urn:ogc:def:srs:", "")
                    if crs_text:
                        supported_crs.add(crs_text)

        if self.debug_log:
            QgsMessageLog.logMessage(
                "add_ows_as_group() supported_crs=" + str(supported_crs),
                "bielefeldGeosuche",
                Qgis.Info
            )

        # Ist Projekt-KBS in supported_crs enthalten?
        # Falls nicht, wird der OWS im amtlichen KBS UTM32N (EPSG:25832) hinzugefügt
        if project_crs not in supported_crs:
            QMessageBox.warning(None,
                f"Der {ows_type} {group_name} unterstützt das Projekt-KBS {project_crs} nicht.",
                f"Unterstützt werden z.B.: {list(supported_crs)[:10]}\n" +
                "Es wird nun versucht, das Thema im amtlichen KBS EPSG:25832 (UTM32N) zum Projekt hinzuzufügen. " +
                "Stellen Sie Ihr Projekt-KBS bitte auf dieses KBS um."
            )
            project_crs = "EPSG:25832"


        # 6. Layernamen und -titel des OWS rekursiv sammeln
        layer_names = {}

        # Nur direkte Kind-Layer durchgehen
        secondElemName = ""
        if ows_type == "WMS":
            secondElemName = "Layer"
        elif ows_type == "WFS":
            secondElemName = "FeatureType"

        child = root_layer.firstChildElement(secondElemName)
        while not child.isNull():
            name_elem = child.firstChildElement("Name")
            title_elem = name_elem.nextSiblingElement("Title")

            if not name_elem.isNull() and not title_elem.isNull():
                name = name_elem.text()
                title = title_elem.text()
                if name and title:
                    layer_names[name] = title

            child = child.nextSiblingElement(secondElemName)

        # 7. Gruppe erstellen
        root = QgsProject.instance().layerTreeRoot()
        group = root.insertGroup(0, group_name + " " + ows_type)

        # 8. Reihenfolge umkehren, um die korrekte Zeichenreihenfolge zu haben
        layers_reversed_order = list(layer_names.keys())
        layers_reversed_order.reverse()

        if self.debug_log:
            QgsMessageLog.logMessage(
                "add_ows_as_group() layers_reversed_order: " + str(layers_reversed_order),
                "bielefeldGeosuche",
                Qgis.Info
            )

        # 9. Layer hinzufügen
        for layer_name in layers_reversed_order:
            uri = ""
            if ows_type == "WMS":
                uri = f"url={ows_url}&layers={layer_name}&styles=&format=image/png&crs={project_crs}"
            elif ows_type == "WFS":
                uri = f"srsname='{project_crs}' typename='{layer_name}' url='{ows_url}'"

            layer = {}
            if ows_type == "WMS":
                layer = QgsRasterLayer(uri, layer_names[layer_name], "WMS")
            elif ows_type == "WFS":
                layer = QgsVectorLayer(uri, layer_names[layer_name], "WFS")

            if layer.isValid():
                QgsProject.instance().addMapLayer(layer, False)
                group.addLayer(layer)
            else:
                QMessageBox.warning(None,
                    f"Fehler",
                    f"Der Layer {layer_name} konnte nicht geladen werden."
                )
